default: all

all: fiducial fiducialLine utils

.PHONY: fiducial
fiducial:
	- cd fiducial && make

.PHONY: fiducialLine
fiducialLine:
	- cd fiducialLine && make

.PHONY: utils
utils:
	- cd utils && make
