default: all

all: bolometric exception ext fiducial isochrone isofit misc modeling population warn

.PHONY: bolometric
bolometric:
	- cd bolometric && make

.PHONY: exception
exception:
	- cd exception && make

.PHONY: ext
ext:
	- cd ext && make

.PHONY: fiducial
fiducial:
	- cd fiducial && make

.PHONY: isochrone
isochrone:
	- cd isochrone && make

.PHONY: isofit
isofit:
	- cd isofit && make

.PHONY: misc
misc:
	- cd misc && make

.PHONY: modeling
modeling:
	- cd modeling && make

.PHONY: population
population:
	- cd population && make
